### ISSUE TITLE
Window errors, previously undefined, and glass type errors 

### ISSUE THREAD

**Issue by TfedUD** [ladybug-tools/honeybee-doe2#41]
on revit sample basic
![image](https://github.com/ladybug-tools/honeybee-doe2/assets/63176386/370f3fcf-5307-4be4-ac3a-6966cbbbc642)

**Comment by mostaphaRoudsari** [comment]
This one is fixed here:

https://github.com/ladybug-tools/honeybee-doe2/pull/50/files#diff-d4ac9bf5dac70ca4c02f7712b31b62846b55781e9f0479c3d18171e525567d14R73-R78
