### ISSUE TITLE
shade geom: duplicate vertices

### ISSUE THREAD

**Issue by TfedUD** [ladybug-tools/honeybee-doe2#42]
![image](https://github.com/ladybug-tools/honeybee-doe2/assets/63176386/bb5e01af-9ed2-440b-83ce-fb1c1e8233f5)
This should be relatively straight forward as routine to prevent duplicate vertices already exist in codebase.

This may be a doughnut geom // equest thing

**Comment by mostaphaRoudsari** [comment]
This one turned out to be the case for a geometry with a hole. The user can fix this case manually by splitting the face.
