### ISSUE TITLE
Translating HBJSON with No Mass Constructions to INP Results in eQuest Errors

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-doe2#91]
Hey @TfedUD and @mostaphaRoudsari ,

This is just to let you know about a bug that isn't a major blocker but it does violate our pact that "any valid model should translate to eQuest without errors." Specifically, if I have a valid HBJSON model with No Mass constructions in it like this one:
https://drive.google.com/file/d/1rt168ouwM4D5WzlZkC6knpjx1UVrNAUL/view?usp=sharing

I get errors when translating it to INP with honeybee-doe2:
![image](https://github.com/ladybug-tools/honeybee-doe2/assets/5567574/0219db06-0b58-4ffc-86b4-40e697c5502e)
![image](https://github.com/ladybug-tools/honeybee-doe2/assets/5567574/08739331-73fb-4d1e-aaf0-dc40f790565c)

It looks like there are also some symbol errors? In any event, here is the INP file that I am currently getting when I translate the HBJSON above using honeybee-doe2:
https://drive.google.com/file/d/1kpIP46Hss9mYR0ut3Kl6HNqbJ7Nh1j8V/view?usp=sharing

I hope this is an easy one to fix by just adding in a small amount of heat capacity for these no-mass constructions.

**Comment by TfedUD** [comment]
Hi @chriswmackey  this is totally my fault, I put off taking care of this bug one to many times, never documented it and forgot.  Learning the importance of documentation!
I think this will be an easy one, should be able to get a fix out today or between today and monday.

The symbol errors occurred due to the previous errors about the heat capacity, once that error is fixed everything else should fall in line.

**Comment by chriswmackey** [comment]
Hey @TfedUD ,
I just wanted to ask about this one since I know that I also just opened up two other issues about unit conversion bugs. I'm happy to try my hand at fixing this if you are busy. Just let me know.

**Comment by TfedUD** [comment]
Hi @chriswmackey! I've been working at it but have ran into some hills, also was working on an app thats now done.
I think I can finish this one soon but if not, I'll definitely take you up on that!

**Comment by chriswmackey** [comment]
Sounds good, @TfedUD . Keep me posted. Remember that you can pretty easily create a material with heat capacity from one with none by choosing some arbitrary material thickness `t` (eg. 1 inch) and just using `R = t / k` to solve for the conductivity `k`, where `R` is the r-value of the no-mass construction. Then, you can specify some lower material density and heat capacity that might be pertinent for insulation. And these will have meaning to DOE-2 because of the thickness you specified.

**Comment by TfedUD** [comment]
Fixed the layers and construction issues, now on these:
![image](https://github.com/ladybug-tools/honeybee-doe2/assets/63176386/7a914b31-8256-40c3-bd0f-3b6d73db6ea5)
We have another same model that doesn't have these issues, I'll  have to compare the two and see whats going on
