### ISSUE TITLE
Switch statements when switch statement case value is none breaks export 

### ISSUE THREAD

**Issue by TfedUD** [ladybug-tools/honeybee-doe2#92]
When there is no ventilation load in a room, and it is exported with ventilation related switch statements, it breaks export.

**Comment by mostaphaRoudsari** [comment]
@TfedUD, is this issue still related? Or has it been addressed with Chris's refactor?

**Comment by TfedUD** [comment]
@mostaphaRoudsari I'm pretty sure its taken care of but I'll double check when I get a chance

**Comment by TfedUD** [comment]
refactor took care of issue
